[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "weather"
path = "main.rs"

[dependencies]
anyhow = "1.0.81"
html2text = { version = "0.12.4" }
reqwest = "0.12.3"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
